version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "9013:9013"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"
